#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building ldtab.ls -> ldtab.js ..."
npx lsc -cp src/ldtab.ls > dist/ldtab.js
echo "minify ldtab.js -> ldtab.min.js ..."
npx uglifyjs dist/ldtab.js > dist/ldtab.min.js

echo "build src/ldtab.styl -> dist/ldtab.css ..."
./node_modules/.bin/stylus -p src/ldtab.styl > dist/ldtab.css
echo "minifying ldtab.css ..."
./node_modules/.bin/uglifycss dist/ldtab.css > dist/ldtab.min.css

echo "copy dist to web ..."
rm -rf web/static/assets/lib/ldtab/dev/
mkdir -p web/static/assets/lib/ldtab/dev/
cp -R dist/* web/static/assets/lib/ldtab/dev/
